### ISSUE TITLE
404 page questions

### ISSUE THREAD

**Issue by epbarger** [rocketinsights/edb_docs#118]
example 404 page - https://edb-docs-pip-eb-404-dqindkn7rl.herokuapp.com/edb-docs/d/edb-postgres-advanced-server/installation-getting-started/installation-guide-for-windows/12/toc.html

Two things came out of the meeting today (July 17)

1. How should we style the "suggested" links? Right now we're reusing the advanced search result, but it seem like a title + link or just a simple link might be nicer

2. Can we make the "404" text in the ascii art a different color? Maybe EDB orange? Just so it stand out more. I'll also be adjusting the 404 svg to be a bit larger.

Thoughts?

**Comment by cero-miedo** [comment]
Agree with both points, @epbarger.

1. Title and link
2. Let's try EDB Orange and scale up the SVG a little.
