### ISSUE TITLE
Support for "latest" as a product version slug

### ISSUE THREAD

**Issue by cero-miedo** [rocketinsights/edb_docs#139]
The base requirement for this is the creation of a "version-agnostic" path structure which smoothly adapts to new versions of product documentation. This exists in the current EDB Docs system, but is sub-optimal (for reasons I'll get into shortly).

There are two primary goals for this feature:

1. **Encourage people to reference the latest version of documentation unless a specific version is required**. Currently, most references to specific topics are contained within the product documentation itself and can thus be relative. We intend to increase the occurrence of references to this documentation across products and from outside of product-specific documentation; with rare exceptions, these references will need to be version-agnostic - we cannot feasibly re-write all references every time a new version is released. We should assume that most writers and editors will take the easy route when adding links, and copy a path or URL from their browsers' address bars.

2. **Encourage search engines to index and rank the most recent version of each product's documentation.** In theory, this should happen as long as the No.1 goal is achieved. In practice, these pages can be slow to re-index and search engines may have a hard time determining which version is "most recent". Some of that is out of scope for this request (timestamps), and other concerns may be addressed simply by moving to faster static pages (Gatsby). However, one piece does tie into this request: **we should not ask search engines to index the same content *twice*, under two different URLs.** Not only is this bad for SEO, it clutters search results.

## Actions to take

In order to achieve both goals outlined above, we should do the following:

1. The latest version of a product's documentation should live on a path with "latest" in place of the version number (the version-agnostic path).
2. The latest version of a product's documentation should still be accessible via a path with that version number in it, **but should redirect (HTTP 302/307) to the version-agnostic path.**
3. When a new version is released, the content accessible via the version-agnostic path *and the versioned-path which redirect to the version-agnostic path* should be updated immediately.

The intended effect then is that for readers / writers / editors, the latest documentation is always accessible via the version-agnostic path (e.g., `/epas/latest`) and version-specific links require extra effort to include. While for search engines, the latest content is always available via the version-agnostic path *and no other path*. Ultimately, this should result in most stable links to product documentation, both internally and from search engines, being to the version-agnostic paths.

## A note on rel=canonical

Everything above is primarily human-focused; it has potential SEO benefits, but the primary focus is on ensuring that *people* both use and see links that are most likely to be useful for them. This section is entirely focused on search engines: ultimately, we want our SEO to be beneficial to the humans searching, but we have limited control there - the best we can do is provide hints to the search engines that they shouldn't waste their resources *or the time and energy of people searching* on pages that are largely duplicates.

This is where [rel=canonical](https://en.wikipedia.org/wiki/Canonical_link_element) comes in. The purpose is to tell the search indexer that a given page corresponds to a given URL *even if it isn't being accessed via that URL*. 

So for instance, right now both `/epas/11/01_epas_inst_linux` and `/epas/12/01_epas_inst_linux` should have the same "canonical URL" - and per the rationale above, it should be the one where the path is `/epas/latest/01_epas_inst_linux`. When version 13 is released, `/epas/latest/01_epas_inst_linux` will *still* have the same canonical URL - but now `/epas/12/01_epas_inst_linux` will have a canonical URL where the path is `/epas/12/01_epas_inst_linux`, while the new page `/epas/13/01_epas_inst_linux` will redirect to `/epas/latest/01_epas_inst_linux` and thus have the canonical URL `/epas/latest/01_epas_inst_linux`. 

Sound confusing? Think of it this way: we're optimizing for the case where someone installing EPAS on Linux wants the latest version of EPAS. Not the version that was latest the last time Google indexed our site, the *latest version* - regardless of what version that might be. We provide a method of switching to a different version on-site, but for the purpose of searching there's just one page - the latest, the *canonical*, installation page.

### Actions to take

Add `<link rel="canonical" href="[version-agnostic-url]">` to all pages served via the version-agnostic URL described above. This will serve to reinforce the importance of that URL in search results *without* requiring us to use a 301 (permanent) redirect for the latest versioned URL (which would be problematic for actual users, as browsers tend to cache these redirects). 

### Gold-plating w/ canonical: all other versions

That last paragraph hints at something else we should at least consider: using rel=canonical to direct search engines to consider *all* versioned pages views onto the same, canonical, information. For example, instead of `/epas/11/01_epas_inst_linux` having a canonical URL containing the path `/epas/11/01_epas_inst_linux`, it could *also* use `/epas/latest/01_epas_inst_linux` as the canonical path. This would, over time, discourage search engines from presenting results from pages other than those in the version-agnostic, "latest" version of the documentation. It does require us to be able to map at least most of the pages within each version to the same, version-agnostic URL however.

An example of this in action can be found in the nodejs documentation. These four pages all have the same canonical URL:

- https://nodejs.org/docs/latest-v7.x/api/http.html
- https://nodejs.org/docs/latest-v14.x/api/http.html
- https://nodejs.org/docs/latest/api/http.html
- https://nodejs.org/api/http.html (this is the canonical URL - it is referenced via `<link rel="canonical" href="https://nodejs.org/api/http.html">` by all three pages above).

(There are *eleven other versions* of that page as well...)

The end result of this is that [searching for nodejs Class: http.ClientRequest](https://www.google.com/search?q=nodejs+Class%3A+http.ClientRequest) returns only *one* result from nodejs.org, instead of the *13 to 15 functionally-identical* results that would otherwise be possible.

We should strongly consider this as well...

**Comment by epbarger** [comment]
Implemented! 

https://github.com/rocketinsights/edb_docs/pull/141
https://github.com/rocketinsights/edb_docs/pull/145
