### ISSUE TITLE
Wildcard redirects

### ISSUE THREAD

**Issue by cero-miedo** [rocketinsights/edb_docs#159]
## Problem Statement

On our old docs site, we've encountered cases of documents being removed from the site, but they are still indexed by Google. Users clicking on these dead links are presented with a 404.

Our product portfolio has limited support windows, so it stands to reason that we may need to remove content. It would be preferable to control this via some sort of global redirect rules within the code base.

**Comment by epbarger** [comment]
It looks like netlify supports wildcard style redirects https://docs.netlify.com/routing/redirects/redirect-options/#splats, so it would be a matter of creating a process to add to the netlify redirects file (which currently is automatically generated at build time). This would only work when deployed, but that's probably okay?

**Comment by epbarger** [comment]
addressed with https://github.com/rocketinsights/edb_docs/commit/07dcc1f194f5e0c7aa8e6157cc867a868b1ee36c
