### ISSUE TITLE
Sitemap for docs site

### ISSUE THREAD

**Issue by josh-heyer** [rocketinsights/edb_docs#161]
Got a request from the web team to generate a sitemap for just the docs site; plan is to have two sitemaps for edb, one for the marketing site (updated by Drupal), the other for Docs (updated by that system).  Might just be able to [drop a plugin](https://www.gatsbyjs.com/docs/creating-a-sitemap/) for this.

**Comment by josh-heyer** [comment]
Evan by his absence volunteered to take this on during our weekly call 😜

**Comment by epbarger** [comment]
Added basic sitemap with https://github.com/rocketinsights/edb_docs/pull/164 . Didn't change any default settings, if anyone has tweaks to suggest let me know :)
