### ISSUE TITLE
convert .mdx files of a product version to PDF

### ISSUE THREAD

**Issue by bradnoble** [rocketinsights/edb_docs#96]
In the field/product sync presentation this am, field techs explained the importance of PDF versions of the docs for customers / users:

> In secure networks, where internet connections aren't available, PDF documents are important.

User story:
As a user, I would expect to be able to click a link on any page of a product's documentation and generate a PDF of that product, of that version, featuring an interactive table of contents.

**Comment by cero-miedo** [comment]
*[Customising pandoc](https://learnbyexample.github.io/tutorial/ebook-generation/customizing-pandoc/) has some insights into how pandoc can be used to generate branded pdfs.

broke: manually generating PDFs and uploading them somewhere
woke: each time a tweak is made to a document set, invoke pandoc on the server to concat all the MDXs, removing the front matter, code highlighting, generating a TOC, caching the build

**Comment by epbarger** [comment]
I think https://github.com/rocketinsights/edb_docs/pull/172 implemented everything we care about. If you think there is something I'm missing let me know! TBD on when we'll regenerate PDFs, right now it's a manual process.
